// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    BlankPage: typeof import('./../components/blank-page.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    LineBarChart: typeof import('./../components/echarts/lineBarChart/index.vue')['default']
    PieChart: typeof import('./../components/echarts/pieChart/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/svg-icon.vue')['default']
  }
}

export {}
